### ISSUE TITLE
ResourceNotFound error on public IP during VM creation

### ISSUE THREAD

**Issue by nicholasmhughes** [eitrtechnologies/idem-azurerm#78]
**Describe the bug**
Creating a public IP along with a VM throws this guy:
```
[ERROR   ] An Azure Network CloudError has occurred: Azure Error: ResourceNotFound
Message: The Resource 'Microsoft.Network/publicIPAddresses/{'id': '' under resource group 'rg-tricycle' was not found.
```

**Include troubleshooting information**
```
#!jinja|yaml

ensure_resource_group_exists:
    azurerm.resource.group.present:
        - name: rg-tricycle
        - location: eastus

ensure_virtual_network_exists:
    azurerm.network.virtual_network.present:
        - name: vnet-trike-eastus-001
        - resource_group: rg-tricycle
        - address_prefixes:
            - "192.168.0.0/16"
        - subnets:
            - name: default
              address_prefix: "192.168.0.0/24"

ensure_virtual_machine_exists:
    azurerm.compute.virtual_machine.present:
        - name: vmidem001
        - resource_group: rg-tricycle
        - vm_size: "Standard_B2S"
        - image: "OpenLogic|CentOS|7.7|latest"
        - virtual_network: vnet-trike-eastus-001
        - subnet: default
        - allocate_public_ip: True
        - ssh_public_keys:
            - /home/nmhughes/.ssh/id_rsa.pub

#!END
```

**Expected behavior**
Don't throw that error...

**Versions (please complete the following information):**
 - Ubuntu 18.04
 - 3.6.9
 - `pip freeze` output
it's been doing it for quite some time... not sure if it's SDK related since that's been pinned for a while.
```
azure-mgmt-compute==4.6.2
azure-mgmt-network==2.7.0
```
